// Datos reales de artesanos de ASCEAC, organizados por pasaje.
// Fuente: Lista Oficial de ASCEAC (padron de socios).
// Nota: por privacidad, los numeros de DNI NO se incluyen aqui.
export interface Artisan {
    id: number;
    name: string;
    pasaje: string;
}

export const artisans: Artisan[] = [
  { id: 1, name: 'Puma Ttito, Brigida', pasaje: 'Pasaje Tullumayu' },
  { id: 2, name: 'Tupayupanqui Jiménez, Jesusa', pasaje: 'Pasaje Tullumayu' },
  { id: 3, name: 'Quispe Ochoa, Felicitas', pasaje: 'Pasaje Tullumayu' },
  { id: 4, name: 'Soncco Ccollque, Marcelino', pasaje: 'Pasaje Tullumayu' },
  { id: 5, name: 'Tincusi Chinchero, Filomena', pasaje: 'Pasaje Tullumayu' },
  { id: 6, name: 'Chara Laime, Yonny', pasaje: 'Pasaje Tullumayu' },
  { id: 7, name: 'Quispe Tunque, Ignacia', pasaje: 'Pasaje Tullumayu' },
  { id: 8, name: 'Quispe Bolivar, Roberto', pasaje: 'Pasaje Tullumayu' },
  { id: 9, name: 'Puma Ttito, Sonia', pasaje: 'Pasaje Tullumayu' },
  { id: 10, name: 'López Pacco, Crisologo', pasaje: 'Pasaje Tullumayu' },
  { id: 11, name: 'Arapa Gómez, Irma Fulgencia', pasaje: 'Pasaje Tullumayu' },
  { id: 12, name: 'Lipia Méndez Yolanda Teresa', pasaje: 'Pasaje Tullumayu' },
  { id: 13, name: 'Moreano de Tintaya, Asunta', pasaje: 'Pasaje Tullumayu' },
  { id: 14, name: 'Alegre Lucana, Tomasa', pasaje: 'Pasaje Tullumayu' },
  { id: 15, name: 'Lipia Méndez, Jesús María', pasaje: 'Pasaje Tullumayu' },
  { id: 16, name: 'Tintaya Moreano, Luz Marina', pasaje: 'Pasaje Tullumayu' },
  { id: 17, name: 'Hualverde Torres, Matilde Rossana', pasaje: 'Pasaje Tullumayu' },
  { id: 18, name: 'Díaz Oros, Gladis', pasaje: 'Pasaje Tullumayu' },
  { id: 19, name: 'Quispe Acuña, Norma', pasaje: 'Pasaje Tullumayu' },
  { id: 20, name: 'Ccoillo Vargas, Salome', pasaje: 'Pasaje Tullumayu' },
  { id: 21, name: 'Ascue Ccoscco, Wenceslao', pasaje: 'Pasaje Tullumayu' },
  { id: 22, name: 'Toledo Tupacyupanqui, Gilbert Manuel', pasaje: 'Pasaje Tullumayu' },
  { id: 23, name: 'Delgado de Condo, Irene', pasaje: 'Pasaje Tullumayu' },
  { id: 24, name: 'Castillo Soto, Ronmell', pasaje: 'Pasaje Tullumayu' },
  { id: 25, name: 'Loayza Yuca, Guadalupe', pasaje: 'Pasaje Tullumayu' },
  { id: 26, name: 'Huillca Huaman Vda. de Mamani, Angélica', pasaje: 'Pasaje Tullumayu' },
  { id: 27, name: 'Huahuasoncco Deza, Juana Livia', pasaje: 'Pasaje Tullumayu' },
  { id: 28, name: 'Becerra Ninan, Santusa', pasaje: 'Pasaje Tullumayu' },
  { id: 29, name: 'Coila Yana, Gumercinda', pasaje: 'Pasaje Tullumayu' },
  { id: 30, name: 'Mejia Paucar, Francisca', pasaje: 'Pasaje Tullumayu' },
  { id: 31, name: 'Ramos Llasac, Segundina', pasaje: 'Pasaje Tullumayu' },
  { id: 32, name: 'Quispe Hilaquita, Elena', pasaje: 'Pasaje Pachacuteq' },
  { id: 33, name: 'Quispe Yana, Elena Faustina', pasaje: 'Pasaje Pachacuteq' },
  { id: 34, name: 'Huaman Choqque, Emilio', pasaje: 'Pasaje Pachacuteq' },
  { id: 35, name: 'Aragón Delgado, Lenin', pasaje: 'Pasaje Pachacuteq' },
  { id: 36, name: 'Copacondori de Quispe, Justina', pasaje: 'Pasaje Pachacuteq' },
  { id: 37, name: 'Almanza Yanqui, Luis Victor', pasaje: 'Pasaje Pachacuteq' },
  { id: 38, name: 'Huamani Sencia, Natividad', pasaje: 'Pasaje Pachacuteq' },
  { id: 39, name: 'Condori Cutipa, Luz Delia', pasaje: 'Pasaje Pachacuteq' },
  { id: 40, name: 'Huaman Rojas, Nelly', pasaje: 'Pasaje Intin Watana' },
  { id: 41, name: 'Luque Carcasi, Nelly Zoraida', pasaje: 'Pasaje Intin Watana' },
  { id: 42, name: 'Velarde de Quispe, Eugenia', pasaje: 'Pasaje Intin Watana' },
  { id: 43, name: 'Quispe Mamani, Hermenegilda Justina', pasaje: 'Pasaje Intin Watana' },
  { id: 44, name: 'Laime Vilca, Alberto', pasaje: 'Pasaje Intin Watana' },
  { id: 45, name: 'Torres Quispe, Sebastiana', pasaje: 'Pasaje Intin Watana' },
  { id: 46, name: 'Huarcaya Inquilltupa, Ricardina', pasaje: 'Pasaje Intin Watana' },
  { id: 47, name: 'Meza Nayhua, Eusebio', pasaje: 'Pasaje Intin Watana' },
  { id: 48, name: 'Camino Arosquipa, Margarita', pasaje: 'Pasaje Intin Watana' },
  { id: 49, name: 'Peralta Huaman, Lourdes', pasaje: 'Pasaje Intin Watana' },
  { id: 50, name: 'Mestas de Choque, Herminia', pasaje: 'Pasaje Intin Watana' },
  { id: 51, name: 'Davalos Concha, Marisol', pasaje: 'Pasaje Inti Raymi' },
  { id: 52, name: 'Mamani Inca, Julia', pasaje: 'Pasaje Inti Raymi' },
  { id: 53, name: 'Orcon Ochoa, Luz Marina', pasaje: 'Pasaje Inti Raymi' },
  { id: 54, name: 'Flores Suyo, Roxana', pasaje: 'Pasaje Inti Raymi' },
  { id: 55, name: 'Zamora Supa, Luis', pasaje: 'Pasaje Inti Raymi' },
  { id: 56, name: 'Quispe Velarde, Juana Olga', pasaje: 'Pasaje Inti Raymi' },
  { id: 57, name: 'Santa Cruz Cusihuaman, Toribia', pasaje: 'Pasaje Inti Raymi' },
  { id: 58, name: 'Huillca de Delgado, Felipa', pasaje: 'Pasaje Inti Raymi' },
  { id: 59, name: 'Monje Nina, Alejandrina', pasaje: 'Pasaje Inti Raymi' },
  { id: 60, name: 'Ccoyuri Chullo, Alejandro', pasaje: 'Pasaje Inti Raymi' },
  { id: 61, name: 'Paquillo Aite, Sabina', pasaje: 'Pasaje Inti Raymi' },
  { id: 62, name: 'Roque Quispe, Nicomedes', pasaje: 'Pasaje Inti Raymi' },
  { id: 63, name: 'Unzueta Huamanñaui, Concepción', pasaje: 'Pasaje Inti Raymi' },
  { id: 64, name: 'Cusihuaman Guitierrez, Genara', pasaje: 'Pasaje Inti Raymi' },
  { id: 65, name: 'Salguero Puma, Octavio', pasaje: 'Pasaje Inti Raymi' },
  { id: 66, name: 'Aguilar Huanaco Vda. de Machaca Margarita Daria', pasaje: 'Pasaje Inti Raymi' },
  { id: 67, name: 'Irco Paucar, Prudencia', pasaje: 'Pasaje Inti Raymi' },
  { id: 68, name: 'Taipe Yabar, Yeni', pasaje: 'Pasaje Inti Raymi' },
  { id: 69, name: 'Martinez Tolcahua, Valeriana', pasaje: 'Pasaje Inti Raymi' },
  { id: 70, name: 'Luna Espeinosa, Nicanor', pasaje: 'Pasaje Tampumachay 3' },
  { id: 71, name: 'Rodriguez Puma, Eugenia', pasaje: 'Pasaje Tampumachay 3' },
  { id: 72, name: 'Huallpa Martinez, Neil Hector', pasaje: 'Pasaje Tampumachay 3' },
  { id: 73, name: 'Bautista Acostupa, Virginia', pasaje: 'Pasaje Tampumachay 3' },
  { id: 74, name: 'Suyo Huanaco, Rosalía', pasaje: 'Pasaje Tampumachay 3' },
  { id: 75, name: 'Gallegos Montalvo, Nicolasa', pasaje: 'Pasaje Tampumachay 3' },
  { id: 76, name: 'Chavez Quispe, Silvia', pasaje: 'Pasaje Choquequirao III' },
  { id: 77, name: 'Nayra Ramos, Edwin', pasaje: 'Pasaje Choquequirao III' },
  { id: 78, name: 'Huarhua de Quispe, Isidora', pasaje: 'Pasaje Choquequirao III' },
  { id: 79, name: 'Condori Ilahuala, Ana Esther', pasaje: 'Pasaje Choquequirao III' },
  { id: 80, name: 'Huaylla Villegas, Margarita', pasaje: 'Pasaje Choquequirao III' },
  { id: 81, name: 'Quispe Romero, Sixto Javier', pasaje: 'Pasaje Choquequirao III' },
  { id: 82, name: 'Condori Ramos, Catalina', pasaje: 'Pasaje Choquequirao III' },
  { id: 83, name: 'Alfonso Flores, Edita', pasaje: 'Pasaje Choquequirao III' },
  { id: 84, name: 'Baños Morales, Marina', pasaje: 'Pasaje Machupicchu III' },
  { id: 85, name: 'Silvia Anchea, Beatriz', pasaje: 'Pasaje Machupicchu III' },
  { id: 86, name: 'Rojas Acuña, Dominga', pasaje: 'Pasaje Machupicchu III' },
  { id: 87, name: 'Quispe Sucasaca, Santusa', pasaje: 'Pasaje Machupicchu III' },
  { id: 88, name: 'Carlos de Huaman, María Pilar', pasaje: 'Pasaje Machupicchu III' },
  { id: 89, name: 'Salguero Huarsaya, Flora', pasaje: 'Pasaje Machupicchu III' },
  { id: 90, name: 'Quispe Boivar, Nieves', pasaje: 'Pasaje Machupicchu III' },
  { id: 91, name: 'Soto Mendoza, Apolinar', pasaje: 'Pasaje Machupicchu III' },
  { id: 92, name: 'del Rio de Caceres, Dominga', pasaje: 'Pasaje Machupicchu III' },
  { id: 93, name: 'Pacheco de Romero, Barbara', pasaje: 'Pasaje Machupicchu III' },
  { id: 94, name: 'Quispe Mamani, Maria', pasaje: 'Pasaje Machupicchu III' },
  { id: 95, name: 'Mina Quispe, Alejandro', pasaje: 'Pasaje Machupicchu III' },
  { id: 96, name: 'Mejia Huamani, Maria', pasaje: 'Pasaje Ollantaytambo III' },
  { id: 97, name: 'Mendoza Zegarra, Gloria', pasaje: 'Pasaje Ollantaytambo III' },
  { id: 98, name: 'Acrota Orosco, Juan Cancio', pasaje: 'Pasaje Ollantaytambo III' },
  { id: 99, name: 'Villalva Chaina, Bernardina', pasaje: 'Pasaje Ollantaytambo III' },
  { id: 100, name: 'Jaimes Choque, María Luisa', pasaje: 'Pasaje Ollantaytambo III' },
  { id: 101, name: 'Ito Mamani, Rosa', pasaje: 'Pasaje Ollantaytambo III' },
  { id: 102, name: 'Copacondori Ttito, Eliseo', pasaje: 'Pasaje Ollantaytambo III' },
  { id: 103, name: 'Velarde Velarde, Gladis', pasaje: 'Pasaje Ollantaytambo III' },
  { id: 104, name: 'Ito Yana, Benito', pasaje: 'Pasaje Ollantaytambo III' },
  { id: 105, name: 'Valdivia Quispe, Ana Anselma', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 106, name: 'Mogollón Villanueva, Víctor', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 107, name: 'Molina Torres, Walter', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 108, name: 'Tunque de Quispe, Nicolasa', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 109, name: 'Champi Huillca, Josefa', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 110, name: 'Pecho Estrada, Dilma Mariella', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 111, name: 'Velarde Bruna, Victoria Ruperta', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 112, name: 'Condori Cuito, Marcia', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 113, name: 'Ancca Huamani, Víctor', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 114, name: 'Ccana Colque, Ruth Isabel', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 115, name: 'Baltazar Curi Anastacia', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 116, name: 'Huahuasonco Deza, Petronila Julia', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 117, name: 'Huaman Jannco, Claudia', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 118, name: 'Huanaco Mamani, Hilda Beatriz', pasaje: 'Pasaje Sacsayhuaman III' },
  { id: 119, name: 'Ccana Balderrama, Mercedes Rosa', pasaje: 'Pasaje Qoricancha II' },
  { id: 120, name: 'Valdez Paucar, Alejandra', pasaje: 'Pasaje Qoricancha II' },
  { id: 121, name: 'Ramos Quispe de Quenaya, Leonarda', pasaje: 'Pasaje Qoricancha II' },
  { id: 122, name: 'Farfan Guillen, Sabina Rosa', pasaje: 'Pasaje Qoricancha II' },
  { id: 123, name: 'Barreda Quispe de Yana, Ines', pasaje: 'Pasaje Qoricancha II' },
  { id: 124, name: 'Huaycochea Quispe, Josefina', pasaje: 'Pasaje Qoricancha II' },
  { id: 125, name: 'Aquino Condo, Juana', pasaje: 'Calle Qapaq Ñan' },
  { id: 126, name: 'Choque Mestas, Yony Alfredo', pasaje: 'Calle Qapaq Ñan' },
  { id: 127, name: 'Salguero Soncco, Santiago', pasaje: 'Calle Qapaq Ñan' },
  { id: 128, name: 'Farfan Quispe, Carmen Elena', pasaje: 'Calle Qapaq Ñan' },
  { id: 129, name: 'Peñalosa de Gamarra, Lidia Marina', pasaje: 'Calle Qapaq Ñan' },
  { id: 130, name: 'Luque Ttito, Julia', pasaje: 'Calle Qapaq Ñan' },
  { id: 131, name: 'Velarde Bruna, Victoria Ruperta', pasaje: 'Calle Qapaq Ñan' },
  { id: 132, name: 'Condori Cuito, Marcia', pasaje: 'Calle Qapaq Ñan' },
  { id: 133, name: 'Ccalla Paricua, Nelly', pasaje: 'Calle Qapaq Ñan' },
  { id: 134, name: 'Soncco Quispe, Leopoldo', pasaje: 'Calle Qapaq Ñan' },
  { id: 135, name: 'Vilca Mamani, Hermelinda Benita', pasaje: 'Calle Qapaq Ñan' },
  { id: 136, name: 'Morales Llacta, Hans Wilian', pasaje: 'Calle Qapaq Ñan' },
  { id: 137, name: 'Huamantalla Huaman, Santusa Yolanda', pasaje: 'Calle Qapaq Ñan' },
  { id: 138, name: 'Coaquira Mamani, Sebastiana', pasaje: 'Calle Qapaq Ñan' },
  { id: 139, name: 'Mendoza Pastor, Carmen', pasaje: 'Calle Qapaq Ñan' },
  { id: 140, name: 'Baca Puma, María Isabel', pasaje: 'Calle Qapaq Ñan' },
  { id: 141, name: 'Salinas Fuentes, Fernando', pasaje: 'Calle Qapaq Ñan' },
  { id: 142, name: 'Cutipa Cutipa, Flaviana', pasaje: 'Calle Qapaq Ñan' },
  { id: 143, name: 'Castillo Vega, Raquel Francisca', pasaje: 'Calle Qapaq Ñan' },
  { id: 144, name: 'Quispe Velarde, Marcusa Gabi', pasaje: 'Calle Qapaq Ñan' },
  { id: 145, name: 'Apaza Condori, Angelino', pasaje: 'Calle Qapaq Ñan' },
  { id: 146, name: 'Quispe Zela, Rubén Florentino', pasaje: 'Calle Qapaq Ñan' },
  { id: 147, name: 'Cutipa Mamani, Matilde', pasaje: 'Calle Qapaq Ñan' },
  { id: 148, name: 'Prieto Angulo, Dimas', pasaje: 'Calle Qapaq Ñan' },
  { id: 149, name: 'Coila Roque, Edwin Helmunt', pasaje: 'Calle Qapaq Ñan' },
  { id: 150, name: 'Zuniga de Escalante, Florencia', pasaje: 'Calle Qapaq Ñan' },
  { id: 151, name: 'Cabrera Alarcon, Clorinda', pasaje: 'Calle Qapaq Ñan' },
  { id: 152, name: 'Apaza Flores, Gregoria', pasaje: 'Calle Qapaq Ñan' },
  { id: 153, name: 'Tacar Vilca, María Luisa', pasaje: 'Calle Qapaq Ñan' },
  { id: 154, name: 'Tucya Huahuachampi, David', pasaje: 'Pasaje Tapumachay 1' },
  { id: 155, name: 'Berrio Huaman, Carmen', pasaje: 'Pasaje Tapumachay 1' },
  { id: 156, name: 'Cabrera Alaron Edwin', pasaje: 'Pasaje Tapumachay 1' },
  { id: 157, name: 'Laurel Valencia, Ubaldo', pasaje: 'Pasaje Tapumachay 1' },
  { id: 158, name: 'Ríos Apaza, Jacoba', pasaje: 'Pasaje Tapumachay 1' },
  { id: 159, name: 'Tunqui Choque, Yolanda', pasaje: 'Pasaje Tapumachay 1' },
  { id: 160, name: 'Lloclle Caparo, Zenobia', pasaje: 'Pasaje Tapumachay 1' },
  { id: 161, name: 'Torres Quispe, Lucia Amanda', pasaje: 'Pasaje Tapumachay 1' },
  { id: 162, name: 'Quispe León, Herminia', pasaje: 'Pasaje Tapumachay 1' },
  { id: 163, name: 'Alegria Choque, Juliana Margarita', pasaje: 'Pasaje Tapumachay 1' },
  { id: 164, name: 'Paredes Arredondo, Felicitas', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 165, name: 'Enrriquez de Chipana, Irene', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 166, name: 'Quispe Lupa, Teodoro', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 167, name: 'Checca de Coralla, Liberata', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 168, name: 'Salguero Vilca, Honorata', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 169, name: 'Salazar Valencia, Lucia Caferina', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 170, name: 'Siwincha de López, Herminia', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 171, name: 'Quispe Cusihuaman, Mario', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 172, name: 'Ramos Condori, Eugenia', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 173, name: 'Huillca Ccapa, Benita', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 174, name: 'Rodríguez Mamani, Martha', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 175, name: 'Cordova Vivas, Nayda', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 176, name: 'Palomino Rivas, Andrés', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 177, name: 'Arapa Gómez, Karina Yaneth', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 178, name: 'Paccha Sutta, Lucia', pasaje: 'Pasaje Ollantaytambo II' },
  { id: 179, name: 'Huallpa Tapara de Choquehuillca, Francisca', pasaje: 'Pasaje Choquequirao II' },
  { id: 180, name: 'Ttito Gonzalez, Juan Pablo', pasaje: 'Pasaje Choquequirao II' },
  { id: 181, name: 'Paucar Flores, Julia', pasaje: 'Pasaje Choquequirao II' },
  { id: 182, name: 'Calla Llanccaya, Fe Erodita', pasaje: 'Pasaje Choquequirao II' },
  { id: 183, name: 'Quispe Mamani, Cecilia', pasaje: 'Pasaje Choquequirao II' },
  { id: 184, name: 'Quispe Yucra, Washinton Willy', pasaje: 'Pasaje Choquequirao II' },
  { id: 185, name: 'Coila Yana, Hilda', pasaje: 'Pasaje Choquequirao II' },
  { id: 186, name: 'Coila Yana, Eustacia Cirila', pasaje: 'Pasaje Choquequirao II' },
  { id: 187, name: 'Since Tinco, Hermelinda', pasaje: 'Pasaje Choquequirao II' },
  { id: 188, name: 'Merma Challco, Victoria', pasaje: 'Pasaje Choquequirao II' },
  { id: 189, name: 'Román Molero, Cristóbal', pasaje: 'Pasaje Choquequirao II' },
  { id: 190, name: 'Llanca y de Quispe, Rosa', pasaje: 'Pasaje Choquequirao II' },
  { id: 191, name: 'Huahuachampi Pacco, Guillermina', pasaje: 'Pasaje Choquequirao II' },
  { id: 192, name: 'Yana Barreda, Esther Irene', pasaje: 'Pasaje Choquequirao II' },
  { id: 193, name: 'Vera Quispe, Margarita', pasaje: 'Pasaje Choquequirao II' },
  { id: 194, name: 'Coila Mamani, Julia Magdalena', pasaje: 'Pasaje Machupicchu II' },
  { id: 195, name: 'Coila Yana, Felipe', pasaje: 'Pasaje Machupicchu II' },
  { id: 196, name: 'Salguero Huarsaya, Eusebio Marcos', pasaje: 'Pasaje Machupicchu II' },
  { id: 197, name: 'Valcarcel Joyas, Francisco Javier', pasaje: 'Pasaje Machupicchu II' },
  { id: 198, name: 'Quispe Condo, Miguel', pasaje: 'Pasaje Machupicchu II' },
  { id: 199, name: 'Perez Chavez, Zenon', pasaje: 'Pasaje Machupicchu II' },
  { id: 200, name: 'Bejar Quispe, Justina', pasaje: 'Pasaje Machupicchu II' },
  { id: 201, name: 'Quispe Huaman, Carlota', pasaje: 'Pasaje Machupicchu II' },
  { id: 202, name: 'Huamanttupa Lozano, Griselda', pasaje: 'Pasaje Machupicchu II' },
  { id: 203, name: 'Ccorimanga Palomino, Haydee', pasaje: 'Pasaje Machupicchu II' },
  { id: 204, name: 'Centeno Florez, Marína Celia', pasaje: 'Pasaje Machupicchu II' },
  { id: 205, name: 'Aguilar Choque, Yola Ignacia', pasaje: 'Pasaje Machupicchu II' },
  { id: 206, name: 'Choqque Huillca, Silveria', pasaje: 'Pasaje Machupicchu II' },
  { id: 207, name: 'Quispe Valeriano, Epifanía', pasaje: 'Pasaje Machupicchu II' },
  { id: 208, name: 'Aguilar Suyo, Zenaida', pasaje: 'Pasaje Machupicchu II' },
  { id: 209, name: 'Levita Callañaupa, Vilma', pasaje: 'Pasaje Machupicchu II' },
  { id: 210, name: 'Guzman Reyes, Bertha Smith', pasaje: 'Pasaje Machupicchu II' },
  { id: 211, name: 'Paucar Flores, Gregoria', pasaje: 'Pasaje Machupicchu II' },
  { id: 212, name: 'Mariano Chara, Abelardo', pasaje: 'Pasaje Tampumachay II' },
  { id: 213, name: 'Ccalla Ticona, Venancia', pasaje: 'Pasaje Tampumachay II' },
  { id: 214, name: 'Salas Muñoz, Victoria', pasaje: 'Pasaje Tampumachay II' },
  { id: 215, name: 'de la Cruz Muñoz, Panfilo', pasaje: 'Pasaje Tampumachay II' },
  { id: 216, name: 'Apaza Quispe, Juana', pasaje: 'Pasaje Tampumachay II' },
  { id: 217, name: 'Almanza Yanque, Sebastiana', pasaje: 'Pasaje Tampumachay II' },
  { id: 218, name: 'Escalante Puma, Placido', pasaje: 'Pasaje Tampumachay II' },
  { id: 219, name: 'Levita de Llancay, Honorata', pasaje: 'Pasaje Tampumachay II' },
  { id: 220, name: 'Chavez Pacheco, Ernesto', pasaje: 'Pasaje Tampumachay II' },
  { id: 221, name: 'Puma Huayna, Jacinta', pasaje: 'Pasaje Tampumachay II' },
  { id: 222, name: 'Ttito Ttito, Alfredo', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 223, name: 'Quiñones Jalisto, Wilbert', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 224, name: 'Concha Anaya, Josefina', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 225, name: 'Parí de Coaquira, Eusebia', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 226, name: 'Palomino Hurtado, Rosa', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 227, name: 'Hilares Vivas, Vilma', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 228, name: 'Ruiz Huaman, Lucia', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 229, name: 'Ccala Saavedra, Rosa', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 230, name: 'Valer Huacho, Benigna', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 231, name: 'Huaman Carrasco, Regina', pasaje: 'Pasaje Riqchary Wayna' },
  { id: 232, name: 'Apaza Callañaupa, Maria Alicia', pasaje: 'Calle Jatun Qosqo' },
  { id: 233, name: 'Bolañoz Rodríguez, Carlos', pasaje: 'Calle Jatun Qosqo' },
  { id: 234, name: 'Chuchullo Zavala, Regina', pasaje: 'Calle Jatun Qosqo' },
  { id: 235, name: 'Gonzales Enriquez, Antonia', pasaje: 'Calle Jatun Qosqo' },
  { id: 236, name: 'Coaquira Mancha, Jorge', pasaje: 'Calle Jatun Qosqo' },
  { id: 237, name: 'Ccora Escalante, Delfina', pasaje: 'Calle Jatun Qosqo' },
  { id: 238, name: 'Lopez Flores, Flora Agustina', pasaje: 'Calle Jatun Qosqo' },
  { id: 239, name: 'Catalán Hilares, Antonio', pasaje: 'Calle Jatun Qosqo' },
  { id: 240, name: 'Salguero Huarsaya, Francisca', pasaje: 'Calle Jatun Qosqo' },
  { id: 241, name: 'Mamani Espirilla, María Praxides', pasaje: 'Calle Jatun Qosqo' },
  { id: 242, name: 'Roque Yanqui, Pedro Juan', pasaje: 'Calle Jatun Qosqo' },
  { id: 243, name: 'Tupacyupanqui Jimenez, Felicitas Amparo', pasaje: 'Calle Jatun Qosqo' },
  { id: 244, name: 'Rojas de Apaza, Paula', pasaje: 'Calle Jatun Qosqo' },
  { id: 245, name: 'Castillo Vega, Alberto Gabriel', pasaje: 'Calle Jatun Qosqo' },
  { id: 246, name: 'Quispe de Moron, Sinforosa Anita', pasaje: 'Pasaje Machupicchu I' },
  { id: 247, name: 'Gallegos Díaz, Fidelia', pasaje: 'Pasaje Machupicchu I' },
  { id: 248, name: 'Cruz de Copacondori, Honorata', pasaje: 'Pasaje Machupicchu I' },
  { id: 249, name: 'Quispe Orue, Marilu', pasaje: 'Pasaje Machupicchu I' },
  { id: 250, name: 'Quispe Pumayalli, Edzon', pasaje: 'Pasaje Machupicchu I' },
  { id: 251, name: 'Quispe Chambi, Filomena', pasaje: 'Pasaje Machupicchu I' },
  { id: 252, name: 'Ccallañaupa Quillahuman, Lucia', pasaje: 'Pasaje Machupicchu I' },
  { id: 253, name: 'Quispe Quilca, Bety', pasaje: 'Pasaje Machupicchu I' },
  { id: 254, name: 'Mamani Yanqui, Sixto Máximo', pasaje: 'Pasaje Machupicchu I' },
  { id: 255, name: 'Cutipa Cutipa, Lidia', pasaje: 'Pasaje Machupicchu I' },
  { id: 256, name: 'Vargas Montesinos, Joaquina', pasaje: 'Pasaje Machupicchu I' },
  { id: 257, name: 'Sicos Puma, Estefanía', pasaje: 'Pasaje Machupicchu I' },
  { id: 258, name: 'Vergara Ccorahua, Juan', pasaje: 'Pasaje Machupicchu I' },
  { id: 259, name: 'Paucar Rodríguez, Cristina', pasaje: 'Pasaje Machupicchu I' },
  { id: 260, name: 'Gutiérrez Baca, Sabina', pasaje: 'Pasaje Machupicchu I' },
  { id: 261, name: 'Carlos Achiri, Carmen Rosa', pasaje: 'Pasaje Machupicchu I' },
  { id: 262, name: 'Guzman Alvarez, Meri', pasaje: 'Pasaje Machupicchu I' },
  { id: 263, name: 'Sihuancha Márquez, Mária Salome', pasaje: 'Pasaje Machupicchu I' },
  { id: 264, name: 'Huaman Alvarez, Marcelina', pasaje: 'Pasaje Machupicchu I' },
  { id: 265, name: 'Vázquez de Pucutuni, Irene', pasaje: 'Pasaje Choque Quirao I' },
  { id: 266, name: 'Amanca Florez, Ascención', pasaje: 'Pasaje Choque Quirao I' },
  { id: 267, name: 'Pereira Aller, Benancia', pasaje: 'Pasaje Choque Quirao I' },
  { id: 268, name: 'Pacuala Melendez, Julia', pasaje: 'Pasaje Choque Quirao I' },
  { id: 269, name: 'Jacho de la Cruz, Justina', pasaje: 'Pasaje Choque Quirao I' },
  { id: 270, name: 'Ccalla Paricahua, Rosa', pasaje: 'Pasaje Choque Quirao I' },
  { id: 271, name: 'Ccuro Velasquez, Nicolasa', pasaje: 'Pasaje Choque Quirao I' },
  { id: 272, name: 'Corrales Luque, Policarpo', pasaje: 'Pasaje Choque Quirao I' },
  { id: 273, name: 'López Bolige, Fortunata', pasaje: 'Pasaje Choque Quirao I' },
  { id: 274, name: 'Suarez Sicclla, Leonarda', pasaje: 'Pasaje Choque Quirao I' },
  { id: 275, name: 'Choquehuillca Huallpa, Virginia', pasaje: 'Pasaje Choque Quirao I' },
  { id: 276, name: 'Condori Ccanchi, Herminia', pasaje: 'Pasaje Choque Quirao I' },
  { id: 277, name: 'Quispe Bellido, Flora', pasaje: 'Pasaje Choque Quirao I' },
  { id: 278, name: 'Pumayalli de Vara, Isabel', pasaje: 'Pasaje Choque Quirao I' },
  { id: 279, name: 'Atamari Achata, Efrain', pasaje: 'Pasaje Choque Quirao I' },
  { id: 280, name: 'Sánchez Frisancho, Yanet', pasaje: 'Pasaje Choque Quirao I' },
  { id: 281, name: 'Florez González, Samuel', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 282, name: 'Lastra Chavez, Lurdez', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 283, name: 'Mendoza Chipana, Bonifacia', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 284, name: 'Quispe Yana, Francisco', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 285, name: 'Díaz Yampi, Ana Mária', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 286, name: 'Mamani Cabrera, Marco Antonio', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 287, name: 'Mamani Champi, Nieves', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 288, name: 'Valer Ccorahua, Félix Fernando', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 289, name: 'Quispe Sallo, Victoria', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 290, name: 'Mamani Mamani, Felicitas', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 291, name: 'Bosa Sánchez, Viviana', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 292, name: 'Quilca Quispe, Ubaldina', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 293, name: 'Neyra Ramos, Olga Magdalena', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 294, name: 'Champí Alarcon, Prudenciana', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 295, name: 'Huaman Qquellon, Luis', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 296, name: 'Condori Ccanchi, Claudia', pasaje: 'Pasaje Ollantaytambo I' },
  { id: 297, name: 'Alvarez Gongora, Manuel Ángel', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 298, name: 'Huaman Castilla, Maximiliana', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 299, name: 'Palomino de Villa, Evarista', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 300, name: 'Levita de Huaman, Luisa', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 301, name: 'Atamari Achata, David Ruben', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 302, name: 'Chisen Quispe, Gladis Pilar', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 303, name: 'Bautista Huaman, Nelly', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 304, name: 'Ccalla Ttito, Luisa', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 305, name: 'Salguero Huarsaya, Cristina', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 306, name: 'Apaza Rojas, Marina', pasaje: 'Pasaje Sacsayhuamanan I' },
  { id: 307, name: 'Quispe Huarilloclla, Alberta', pasaje: 'Pasaje Qoricancha I' },
  { id: 308, name: 'Romero Estrada, Adriel', pasaje: 'Pasaje Qoricancha I' },
  { id: 309, name: 'Vitorino Quispe, Luis', pasaje: 'Pasaje Qoricancha I' },
  { id: 310, name: 'Cabrera Navarrete, Clotilde', pasaje: 'Pasaje Qoricancha I' },
  { id: 311, name: 'Jachu Paccosoncco, Filomena', pasaje: 'Pasaje Qoricancha I' },
  { id: 312, name: 'Arapa Gómez, Carlos Antonio', pasaje: 'Pasaje Qoricancha I' },
  { id: 313, name: 'Yucra Velazque, Francisca', pasaje: 'Pasaje Qoricancha I' },
  { id: 314, name: 'Mamani de Soto, María Mauricia', pasaje: 'Pasaje Qoricancha I' },
  { id: 315, name: 'Baca Huaman, Zenobia', pasaje: 'Pasaje Qoricancha I' },
  { id: 316, name: 'Ttito Apaza, Rufino', pasaje: 'Pasaje Qoricancha I' },
  { id: 317, name: 'Corrales Huaman, Patricia', pasaje: 'Pasaje Qoricancha I' },
  { id: 318, name: 'Valdivia Quispe, Marcelina', pasaje: 'Pasaje Qoricancha I' },
  { id: 319, name: 'Lampa Velarde, Reyna', pasaje: 'Pasaje Qoricancha I' },
  { id: 320, name: 'Choque Mamani, Guillermina', pasaje: 'Pasaje Qoricancha I' },
  { id: 321, name: 'Chahuara Taco, Alejandro', pasaje: 'Pasaje Qoricancha I' },
  { id: 322, name: 'Huaman Llihuac, Cleofe Celia', pasaje: 'Pasaje Qoricancha I' },
  { id: 323, name: 'Arce Rodriguez, Rosa', pasaje: 'Pasaje Qoricancha I' },
  { id: 324, name: 'Aguilar Choque, Evarista', pasaje: 'Pasaje Qoricancha I' },
  { id: 325, name: 'Paucar Rodriguez, Carmen Rosa', pasaje: 'Pasaje Qoricancha I' },
  { id: 326, name: 'Charca de Canaza, Angela', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 327, name: 'Challco Ccanahuire, Martina', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 328, name: 'Mamani Sumerente, Domitila', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 329, name: 'Roque Mamani, Roger Aurelio', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 330, name: 'Concha Anaya, Doris', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 331, name: 'Velazquez Yucra, Julia', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 332, name: 'Quispe Ordoñez, Francisca', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 333, name: 'Escalante Puma, Marina', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 334, name: 'Suarez Ibarra, Grimaldo', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 335, name: 'Aller Mojonero, Wilbert', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 336, name: 'Accostupa Sallo, Tomasa', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 337, name: 'Salguero Huarsaya, Melquiades Hermogenes', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 338, name: 'Quiroz Hernández, Julia', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 339, name: 'Mescco Pumayalli, Cristina', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 340, name: 'Mejia Machaca, Epifania', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 341, name: 'Amaru Queslloya, Fulgencia', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 342, name: 'Parque Lima, Antonia', pasaje: 'Pasaje Sacsayhuaman II' },
  { id: 343, name: 'Puma Huamani, Leandra', pasaje: 'Pasaje Sacsayhuaman II' },
  ];
export const pasajesList: string[] = [
    'Todos',
    'Pasaje Tullumayu',
    'Pasaje Pachacuteq',
    'Pasaje Intin Watana',
    'Pasaje Inti Raymi',
    'Pasaje Tampumachay 3',
    'Pasaje Choquequirao III',
    'Pasaje Machupicchu III',
    'Pasaje Ollantaytambo III',
    'Pasaje Sacsayhuaman III',
    'Pasaje Qoricancha II',
    'Calle Qapaq Ñan',
    'Pasaje Tapumachay 1',
    'Pasaje Ollantaytambo II',
    'Pasaje Choquequirao II',
    'Pasaje Machupicchu II',
    'Pasaje Tampumachay II',
    'Pasaje Riqchary Wayna',
    'Calle Jatun Qosqo',
    'Pasaje Machupicchu I',
    'Pasaje Choque Quirao I',
    'Pasaje Ollantaytambo I',
    'Pasaje Sacsayhuamanan I',
    'Pasaje Qoricancha I',
    'Pasaje Sacsayhuaman II',
  ];
